"""
excel_writer.py

Writes results incrementally to the workbook generated by
generate_template.py. The workbook itself is the checkpoint: on restart,
rows (model_name, prompt_id) already present in each sheet are read and
skipped - no separate state file needed.

WARNING: don't keep ghigliottina_results.xlsx open in Excel while the
batch is running - Windows locks it for writing and the save fails.
"""
import logging
import time
from pathlib import Path

from openpyxl import load_workbook
from openpyxl.workbook import Workbook
from openpyxl.worksheet.worksheet import Worksheet

logger = logging.getLogger(__name__)


class ResultsWriter:
    """Handles reading prior state and writing incrementally."""

    def __init__(self, xlsx_path: Path, columns: list[str]):
        self.xlsx_path = xlsx_path
        self.columns = columns
        self._col_index = {name: idx + 1 for idx, name in enumerate(columns)}

        if not xlsx_path.exists():
            raise FileNotFoundError(
                f"{xlsx_path} does not exist. Generate the template first with generate_template.py"
            )

        self.workbook: Workbook = load_workbook(xlsx_path)
        logger.info(f"Workbook loaded: {xlsx_path} (sheets: {self.workbook.sheetnames})")

    def completed_pairs(self, sheet_name: str) -> set[tuple[str, str]]:
        """Returns the (model_name, prompt_id) pairs already completed successfully.

        A row with status="timeout" or "error" does NOT count as
        completed: it must remain retryable on the next restart. Rows
        without a status column (written before that field existed) are
        treated as completed, for compatibility with data collected
        before this field was added.
        """
        ws = self._get_sheet(sheet_name)
        model_col = self._col_index["model_name"] - 1
        prompt_col = self._col_index["prompt_id"] - 1
        status_col = self._col_index.get("status")
        status_col = status_col - 1 if status_col else None

        done = set()
        for row in ws.iter_rows(min_row=2, values_only=True):
            model_value = row[model_col]
            prompt_value = row[prompt_col]
            if not model_value or not prompt_value:
                continue
            if status_col is not None:
                status_value = row[status_col]
                if status_value is not None and status_value != "ok":
                    continue
            done.add((str(model_value), str(prompt_value)))
        return done

    def append_row(
            self,
            sheet_name: str,
            row_data: dict,
            max_retries: int = 3,
            retry_delay_s: float = 5.0,
    ) -> None:
        """Writes a row for (model_name, prompt_id) and saves to disk right away.

        Upsert, not just append: if a row already exists for the same
        combination (e.g. a timeout that was retried successfully), it is
        overwritten in place instead of adding a second one - otherwise a
        successful retry would leave both the old timeout row and the new
        ok row for the same combination, double-counting it in analysis.

        Retries if the file is momentarily busy (e.g. open in Excel for a
        quick check) before giving up.
        """
        ws = self._get_sheet(sheet_name)
        target_row = self._find_row(ws, row_data.get("model_name"), row_data.get("prompt_id"))
        if target_row is None:
            target_row = ws.max_row + 1

        for col_name, value in row_data.items():
            if col_name not in self._col_index:
                logger.warning(f"Unknown column ignored: {col_name}")
                continue
            ws.cell(row=target_row, column=self._col_index[col_name], value=value)

        for attempt in range(1, max_retries + 1):
            try:
                self.workbook.save(self.xlsx_path)
                return
            except PermissionError:
                logger.warning(
                    f"File {self.xlsx_path} busy (open in Excel?), "
                    f"attempt {attempt}/{max_retries}..."
                )
                if attempt < max_retries:
                    time.sleep(retry_delay_s)

        logger.error(
            f"Save failed after {max_retries} attempts: close "
            f"{self.xlsx_path} in Excel if it's open and rerun the script "
            f"(it will resume from this row)."
        )
        raise PermissionError(f"Could not save {self.xlsx_path}")

    def _find_row(self, ws: Worksheet, model_name, prompt_id) -> int | None:
        """Looks for an existing row for (model_name, prompt_id). None if absent."""
        if model_name is None or prompt_id is None:
            return None
        model_col = self._col_index["model_name"] - 1
        prompt_col = self._col_index["prompt_id"] - 1
        for row_idx, row in enumerate(ws.iter_rows(min_row=2, values_only=True), start=2):
            if row[model_col] == model_name and row[prompt_col] == prompt_id:
                return row_idx
        return None

    def _get_sheet(self, sheet_name: str) -> Worksheet:
        if sheet_name not in self.workbook.sheetnames:
            raise ValueError(f"Sheet '{sheet_name}' not found in workbook")
        return self.workbook[sheet_name]
